In [1]:
# Read in the tab delimited file into an object. Note the full path of the file.
UN_VotingData <- read.table("C:/Users/ramani/Documents/UN Voting Data for DataCamp Class/RawVotingdata.txt", sep = '\t', header = T)

In [2]:
# Display the object
UN_VotingData

        ccode session rcid vote
1         500       1    3    9
2         331       1    3    9
3         935       1    3    9
4         651       1    3    2
5         700       1    3    9
6         692       1    3    9
7         580       1    3    9
8         947       1    3    9
9         225       1    3    9
10        310       1    3    9
11        355       1    3    9
12        775       1    3    9
13         31       1    3    9
14        520       1    3    9
15        435       1    3    9
16        516       1    3    9
17        230       1    3    9
18        452       1    3    9
19        352       1    3    9
20        780       1    3    9
21         91       1    3    1
22        481       1    3    9
23        522       1    3    9
24        305       1    3    9
25        373       1    3    9
26        663       1    3    9
27         94       1    3    1
28         92       1    3    1
29        436       1    3    9
30         53       1    3    9
...       ...     ...  ...  ...
1052576   349      22 9056    9
1052577   775      22 9056    8
1052578   435      22 9056    3
1052579    52      22 9056    1
1052580   260      22 9056    9
1052581   651      22 9056    3
1052582   947      22 9056    9
1052583   365      22 9056    1
1052584   373      22 9056    9
1052585   571      22 9056    1
1052586   482      22 9056    1
1052587   541      22 9056    9
1052588    31      22 9056    9
1052589   511      22 9056    9
1052590   970      22 9056    9
1052591    92      22 9056    2
1052592   225      22 9056    9
1052593   663      22 9056    3
1052594   338      22 9056    2
1052595   750      22 9056    1
1052596   850      22 9056    2
1052597   212      22 9056    1
1052598   380      22 9056    1
1052599   150      22 9056    1
1052600   900      22 9056    1
1052601   130      22 9056    2
1052602   712      22 9056    1
1052603   350      22 9056    2
1052604   305      22 9056    1
1052605   690      22 9056    3

In [5]:
# Change the order of columns into a new object. The comma indicates all rows, the values inside the curly brackets
# are the column indexes in the original dataset
UN_VotingData2 <- UN_VotingData[,c(3,2,4,1)]

In [6]:
# rcid is Roll Call ID, session is the year long session in UN's history, vote is the country's choice 1 = yes, 2 = abstain,
# 3 = no, 9 = not present, 9 = country not yet a UN member, ccode is the country code to uniquely specify the country
UN_VotingData2

        rcid session vote ccode
1          3       1    9   500
2          3       1    9   331
3          3       1    9   935
4          3       1    2   651
5          3       1    9   700
6          3       1    9   692
7          3       1    9   580
8          3       1    9   947
9          3       1    9   225
10         3       1    9   310
11         3       1    9   355
12         3       1    9   775
13         3       1    9    31
14         3       1    9   520
15         3       1    9   435
16         3       1    9   516
17         3       1    9   230
18         3       1    9   452
19         3       1    9   352
20         3       1    9   780
21         3       1    1    91
22         3       1    9   481
23         3       1    9   522
24         3       1    9   305
25         3       1    9   373
26         3       1    9   663
27         3       1    1    94
28         3       1    1    92
29         3       1    9   436
30         3       1    9    53
...      ...     ...  ...   ...
1052576 9056      22    9   349
1052577 9056      22    8   775
1052578 9056      22    3   435
1052579 9056      22    1    52
1052580 9056      22    9   260
1052581 9056      22    3   651
1052582 9056      22    9   947
1052583 9056      22    1   365
1052584 9056      22    9   373
1052585 9056      22    1   571
1052586 9056      22    1   482
1052587 9056      22    9   541
1052588 9056      22    9    31
1052589 9056      22    9   511
1052590 9056      22    9   970
1052591 9056      22    2    92
1052592 9056      22    9   225
1052593 9056      22    3   663
1052594 9056      22    2   338
1052595 9056      22    1   750
1052596 9056      22    2   850
1052597 9056      22    1   212
1052598 9056      22    1   380
1052599 9056      22    1   150
1052600 9056      22    1   900
1052601 9056      22    2   130
1052602 9056      22    1   712
1052603 9056      22    2   350
1052604 9056      22    1   305
1052605 9056      22    3   690

In [9]:
summary(UN_VotingData2)

      rcid         session           vote           ccode
 Min.   :   3   Min.   : 1.00   Min.   :1.000   Min.   :  2.0
 1st Qu.:1338   1st Qu.:26.00   1st Qu.:1.000   1st Qu.:290.0
 Median :2674   Median :38.00   Median :1.000   Median :452.0
 Mean   :2724   Mean   :37.58   Mean   :3.634   Mean   :469.8
 3rd Qu.:4024   3rd Qu.:51.00   3rd Qu.:8.000   3rd Qu.:680.0
 Max.   :9056   Max.   :69.00   Max.   :9.000   Max.   :990.0
                                NA's   :15714   NA's   :81

In [10]:
str(UN_VotingData2)

'data.frame':	1052605 obs. of  4 variables:
 $ rcid   : num  3 3 3 3 3 3 3 3 3 3 ...
 $ session: num  1 1 1 1 1 1 1 1 1 1 ...
 $ vote   : num  9 9 9 2 9 9 9 9 9 9 ...
 $ ccode  : int  500 331 935 651 700 692 580 947 225 310 ...

In [11]:
dim(UN_VotingData2)

[1] 1052605       4

In [31]:
# Since we only care about yes, no, and abstain votes, we pipe the dataset through the filter function
# In the filter function, we define a condition
# make sure to attach both the dplyr and magrittr packages before running the pipe statement!
library(magrittr)
library(dplyr)
# Notice how the output of pipe is passed to a new object....
UN_VotingData3 <- UN_VotingData2 %>% filter(UN_VotingData2$vote <= 3)
# check the size of the new dataset
dim(UN_VotingData3)

[1] 711275      4

In [32]:
# The session variable is a bit tough to interpret. If the first UN session was held in 1945, then each session is a
# count after 1945. We use the MUTATE pipe to do this
UN_VotingData4 <- UN_VotingData3 %>% mutate(year = session + 1945)
UN_VotingData4

       rcid session vote ccode year
1         3       1    2   651 1946
2         3       1    1    91 1946
3         3       1    1    94 1946
4         3       1    1    92 1946
5         3       1    3   220 1946
6         3       1    1   165 1946
7         3       1    1   155 1946
8         3       1    1   130 1946
9         3       1    1   160 1946
10        3       1    1    41 1946
11        3       1    3   210 1946
12        3       1    1    95 1946
13        3       1    1   840 1946
14        3       1    1   140 1946
15        3       1    1   652 1946
16        3       1    1   630 1946
17        3       1    1   100 1946
18        3       1    1   145 1946
19        3       1    2   660 1946
20        3       1    1   101 1946
21        3       1    3   900 1946
22        3       1    1   290 1946
23        3       1    3   369 1946
24        3       1    3   713 1946
25        3       1    3   350 1946
26        3       1    3   560 1946
27        3       1    1   135 1946
28        3       1    3   920 1946
29        3       1    3   450 1946
30        3       1    3   370 1946
...     ...     ...  ...   ...  ...
711246 9056      22    1   375 1967
711247 9056      22    1   390 1967
711248 9056      22    2   230 1967
711249 9056      22    3   510 1967
711250 9056      22    3   520 1967
711251 9056      22    3   551 1967
711252 9056      22    1   369 1967
711253 9056      22    1   210 1967
711254 9056      22    1   355 1967
711255 9056      22    1   434 1967
711256 9056      22    3   435 1967
711257 9056      22    1    52 1967
711258 9056      22    3   651 1967
711259 9056      22    1   365 1967
711260 9056      22    1   571 1967
711261 9056      22    1   482 1967
711262 9056      22    2    92 1967
711263 9056      22    3   663 1967
711264 9056      22    2   338 1967
711265 9056      22    1   750 1967
711266 9056      22    2   850 1967
711267 9056      22    1   212 1967
711268 9056      22    1   380 1967
711269 9056      22    1   150 1967
711270 9056      22    1   900 1967
711271 9056      22    2   130 1967
711272 9056      22    1   712 1967
711273 9056      22    2   350 1967
711274 9056      22    1   305 1967
711275 9056      22    3   690 1967

In [49]:
# Now convert the ccodes into country names. To do this load the COUNTRYCODE package and used chained pipes
# install.packages("countrycode", repos='http://cran.us.r-project.org')
library(countrycode)

votes_processed <- UN_VotingData %>%
  filter(vote <= 3) %>%
  mutate(year = session + 1945) %>%
  mutate(country = countrycode(ccode, "cown", "country.name"))
votes_processed
dim(votes_processed)

# In the above chained pipes, I have done all previous steps at the same time

       ccode session rcid vote year                           country
1        651       1    3    2 1946                             Egypt
2         91       1    3    1 1946                          Honduras
3         94       1    3    1 1946                        Costa Rica
4         92       1    3    1 1946                       El Salvador
5        220       1    3    3 1946                            France
6        165       1    3    1 1946                           Uruguay
7        155       1    3    1 1946                             Chile
8        130       1    3    1 1946                           Ecuador
9        160       1    3    1 1946                         Argentina
10        41       1    3    1 1946                             Haiti
11       210       1    3    3 1946                       Netherlands
12        95       1    3    1 1946                            Panama
13       840       1    3    1 1946                       Philippines
14       140       1    3    1 1946                            Brazil
15       652       1    3    1 1946              Syrian Arab Republic
16       630       1    3    1 1946         Iran, Islamic Republic of
17       100       1    3    1 1946                          Colombia
18       145       1    3    1 1946   Bolivia, Plurinational State of
19       660       1    3    2 1946                           Lebanon
20       101       1    3    1 1946 Venezuela, Bolivarian Republic of
21       900       1    3    3 1946                         Australia
22       290       1    3    1 1946                            Poland
23       369       1    3    3 1946                           Ukraine
24       713       1    3    3 1946         Taiwan, Province of China
25       350       1    3    3 1946                            Greece
26       560       1    3    3 1946                      South Africa
27       135       1    3    1 1946                              Peru
28       920       1    3    3 1946                       New Zealand
29       450       1    3    3 1946                           Liberia
30       370       1    3    3 1946                           Belarus
...      ...     ...  ...  ...  ...                               ...
711246   375      22 9056    1 1967                           Finland
711247   390      22 9056    1 1967                           Denmark
711248   230      22 9056    2 1967                             Spain
711249   510      22 9056    3 1967      Tanzania, United Republic of
711250   520      22 9056    3 1967                           Somalia
711251   551      22 9056    3 1967                            Zambia
711252   369      22 9056    1 1967                           Ukraine
711253   210      22 9056    1 1967                       Netherlands
711254   355      22 9056    1 1967                          Bulgaria
711255   434      22 9056    1 1967                             Benin
711256   435      22 9056    3 1967                        Mauritania
711257    52      22 9056    1 1967               Trinidad and Tobago
711258   651      22 9056    3 1967                             Egypt
711259   365      22 9056    1 1967                Russian Federation
711260   571      22 9056    1 1967                          Botswana
711261   482      22 9056    1 1967          Central African Republic
711262    92      22 9056    2 1967                       El Salvador
711263   663      22 9056    3 1967                            Jordan
711264   338      22 9056    2 1967                             Malta
711265   750      22 9056    1 1967                             India
711266   850      22 9056    2 1967                         Indonesia
711267   212      22 9056    1 1967                        Luxembourg
711268   380      22 9056    1 1967                            Sweden
711269   150      22 9056    1 1967                          Paraguay
711270   900      22 9056    1 1967                         Australia
711271   130      22 9056    2 1967                           Ecuador
711272   712      22 9056    1 1967                          Mongolia
711273   350      22 9056    2 1967                            Greece
711274   305      22 9056    1 1967                           Austria
711275   690      22 9056    3 1967                            Kuwait

[1] 711275      6

In [45]:
summary(votes_processed)
class(votes_processed)

     ccode          session           rcid           vote            year
 Min.   :  2.0   Min.   : 1.00   Min.   :   3   Min.   :1.000   Min.   :1946
 1st Qu.:220.0   1st Qu.:32.00   1st Qu.:1823   1st Qu.:1.000   1st Qu.:1977
 Median :438.0   Median :41.00   Median :3066   Median :1.000   Median :1986
 Mean   :447.1   Mean   :41.41   Mean   :3014   Mean   :1.278   Mean   :1986
 3rd Qu.:660.0   3rd Qu.:54.00   3rd Qu.:4235   3rd Qu.:1.000   3rd Qu.:1999
 Max.   :990.0   Max.   :68.00   Max.   :9056   Max.   :3.000   Max.   :2013
   country
 Length:711275
 Class :character
 Mode  :character

[1] "data.frame"

In [52]:
# Once more we change the order of columns
votes_processed <- votes_processed[,c(3,2,4,1,5,6)]
votes_processed

       rcid session vote ccode year                           country
1         3       1    2   651 1946                             Egypt
2         3       1    1    91 1946                          Honduras
3         3       1    1    94 1946                        Costa Rica
4         3       1    1    92 1946                       El Salvador
5         3       1    3   220 1946                            France
6         3       1    1   165 1946                           Uruguay
7         3       1    1   155 1946                             Chile
8         3       1    1   130 1946                           Ecuador
9         3       1    1   160 1946                         Argentina
10        3       1    1    41 1946                             Haiti
11        3       1    3   210 1946                       Netherlands
12        3       1    1    95 1946                            Panama
13        3       1    1   840 1946                       Philippines
14        3       1    1   140 1946                            Brazil
15        3       1    1   652 1946              Syrian Arab Republic
16        3       1    1   630 1946         Iran, Islamic Republic of
17        3       1    1   100 1946                          Colombia
18        3       1    1   145 1946   Bolivia, Plurinational State of
19        3       1    2   660 1946                           Lebanon
20        3       1    1   101 1946 Venezuela, Bolivarian Republic of
21        3       1    3   900 1946                         Australia
22        3       1    1   290 1946                            Poland
23        3       1    3   369 1946                           Ukraine
24        3       1    3   713 1946         Taiwan, Province of China
25        3       1    3   350 1946                            Greece
26        3       1    3   560 1946                      South Africa
27        3       1    1   135 1946                              Peru
28        3       1    3   920 1946                       New Zealand
29        3       1    3   450 1946                           Liberia
30        3       1    3   370 1946                           Belarus
...     ...     ...  ...   ...  ...                               ...
711246 9056      22    1   375 1967                           Finland
711247 9056      22    1   390 1967                           Denmark
711248 9056      22    2   230 1967                             Spain
711249 9056      22    3   510 1967      Tanzania, United Republic of
711250 9056      22    3   520 1967                           Somalia
711251 9056      22    3   551 1967                            Zambia
711252 9056      22    1   369 1967                           Ukraine
711253 9056      22    1   210 1967                       Netherlands
711254 9056      22    1   355 1967                          Bulgaria
711255 9056      22    1   434 1967                             Benin
711256 9056      22    3   435 1967                        Mauritania
711257 9056      22    1    52 1967               Trinidad and Tobago
711258 9056      22    3   651 1967                             Egypt
711259 9056      22    1   365 1967                Russian Federation
711260 9056      22    1   571 1967                          Botswana
711261 9056      22    1   482 1967          Central African Republic
711262 9056      22    2    92 1967                       El Salvador
711263 9056      22    3   663 1967                            Jordan
711264 9056      22    2   338 1967                             Malta
711265 9056      22    1   750 1967                             India
711266 9056      22    2   850 1967                         Indonesia
711267 9056      22    1   212 1967                        Luxembourg
711268 9056      22    1   380 1967                            Sweden
711269 9056      22    1   150 1967                          Paraguay
711270 9056      22    1   900 1967                         Australia
711271 9056      22    2   130 1967                           Ecuador
711272 9056      22    1   712 1967                          Mongolia
711273 9056      22    2   350 1967                            Greece
711274 9056      22    1   305 1967                           Austria
711275 9056      22    3   690 1967                            Kuwait

In [58]:
# Now we use SUMMARIZE to begin aggregating the data. The ground rule is that if a country votes YES on a majority
# of resolutions we assume it votes along international consensus. If NO, the alternative assumption.
# We can use SUMMARIZE to calculcate the number of rows as:
votes_processed %>% summarize(total = n())
# the output of the above statement is the total number of rows. This output may be passed to an object if desired.
# n() is a special function within SUMMARIZE meaning 'the number of rows.' So the above statement gives the total
# number of rows in the dataframe.

   total
1 711275

In [63]:
# Now we want to calculate the percent yes votes.
votes_processed %>% summarize(total = n(), percent_yes = (mean(vote == 1)*100))

   total percent_yes
1 711275    79.63952

In [64]:
# the above output tells us that 79.6 percent of votes have been yes-es in the history of the UN. But has this
# percentage changed over time?
# we use groupby() - before the summarize operation - Groupby() tells SUMMARIZE to create one row for each subgroup
# instead of one overall row
# since we want to check the change of yes votes over time, we group by year first
votes_processed %>% group_by(year) %>% summarize(total = n(), percent_yes = (mean(vote == 1)*100))

    year total      percent_yes
1   1946  2143 57.3495100326645
2   1947  2039 56.9396763119176
3   1948  5685 40.2462620932278
4   1949  3469 43.7590083597579
5   1950  3079  50.730756739201
6   1951  1434 58.5076708507671
7   1952  2882 53.4004163775156
8   1953  1537 63.1750162654522
9   1954  1788  62.248322147651
10  1955  2169 69.4790225910558
11  1956  5126 67.6355833008194
12  1957  2708 60.8567208271787
13  1958  2625 66.5904761904762
14  1959  4326 58.8072122052705
15  1960  9835 54.3873919674631
16  1961  7482 57.2975140336808
17  1962  4642 59.9956915122792
18  1963  3308 72.9443772672309
19  1964   112 1.78571428571429
20  1965  4382 70.7895937927887
21  1966  5868 61.1111111111111
22  1967  6446 61.8057710207881
23  1968  5888 59.8505434782609
24  1969  4942 66.4912990692028
25  1970  7498 69.1117631368365
26  1971 14648 71.4227198252321
27  1972 13355 77.9333582927742
28  1973 11521 77.1894800798542
29  1974  9729 76.9041011409189
30  1975  8987 81.9628352064093
...  ...   ...              ...
39  1984 21986 85.2815427999636
40  1985 22775 84.1844127332601
41  1986 23193 85.0256542922433
42  1987 22067 87.4473195268954
43  1988 20469 86.8093214128682
44  1989 17378 88.3070548969962
45  1990 12678 88.0265026029342
46  1991 11357 85.5859822136128
47  1992 11439 81.7641402220474
48  1993 10272 79.7702492211838
49  1994 10695 81.3090229079009
50  1995 12645 80.9410834321866
51  1996 12272 82.0811603650587
52  1997 11106  80.749144606519
53  1998  9832  83.340113913751
54  1999 10596 81.4458286145715
55  2000 10780  83.330241187384
56  2001 10355 81.1781747947851
57  2002 12174 81.8054871036635
58  2003 13099 81.2199404534697
59  2004 12707 80.6484614779256
60  2005 12655 82.2994863690241
61  2006 15293 82.0636892696005
62  2007 13539 81.0768889873698
63  2008 12907 82.2964282947238
64  2009 12112  80.217965653897
65  2010 11869 82.5427584463729
66  2011 11453 81.1053872347856
67  2012 12335 82.2051074179165
68  2013 11531 80.7041887086983

In [67]:
# How many countries have voted yes over the lifetime of the UN?
# Group_by country, summarize, and save the output in the by_country object and print out this object
by_country <- votes_processed %>%
  group_by(country) %>% summarize(total = n(), percent_yes = (mean(vote == 1)*100))
by_country

                              country total      percent_yes
1                         Afghanistan  4824 83.8101160862355
2                             Albania  3363 72.0487659827535
3                             Algeria  4374 89.7805212620028
4                             Andorra  1410 65.1063829787234
5                              Angola  2950 92.2372881355932
6                 Antigua and Barbuda  2521 91.7096390321301
7                           Argentina  5207 77.4342231611292
8                             Armenia  1479 75.9296822177147
9                           Australia  5245 55.4242135367016
10                            Austria  4786 63.2051817801922
11                         Azerbaijan  1434 85.7043235704324
12                            Bahamas  3547 88.8920214265576
13                            Bahrain  3965 93.3417402269861
14                         Bangladesh  3631 93.8859818231892
15                           Barbados  3958 90.6013137948459
16                            Belarus  5179 74.3386754199652
17                            Belgium  5238 49.2554410080183
18                             Belize  2300 93.0434782608696
19                              Benin  4234 89.9149740198394
20                             Bhutan  3652 91.2376779846659
21    Bolivia, Plurinational State of  4920 84.2682926829268
22             Bosnia and Herzegovina  1145 69.6069868995633
23                           Botswana  3778  92.350449973531
24                             Brazil  5220 80.9578544061303
25                  Brunei Darussalam  2546 93.0871956009426
26                           Bulgaria  4744 69.1821247892074
27                       Burkina Faso  4320 90.1851851851852
28                            Burundi  3925 91.5923566878981
29                         Cabo Verde  3153 94.5448778940691
30                           Cambodia  3573 88.9168765743073
...                               ...   ...              ...
171              Syrian Arab Republic  4858 83.8616714697406
172         Taiwan, Province of China  1233 57.0154095701541
173                        Tajikistan  1121 82.9616413916146
174      Tanzania, United Republic of  4297  91.040260646963
175                          Thailand  5129 84.6948722947943
176                       Timor-Leste   697  96.700143472023
177                              Togo  4504 90.1865008880995
178                             Tonga   775 73.0322580645161
179               Trinidad and Tobago  4205  92.294887039239
180                           Tunisia  4701 90.6615613699213
181                            Turkey  5164 70.2168861347792
182                      Turkmenistan   877 90.7639680729761
183                            Tuvalu   576 82.4652777777778
184                            Uganda  4036 89.8909811694747
185                           Ukraine  5232 71.1391437308868
186              United Arab Emirates  3877 94.1965437193707
187                    United Kingdom  5218 42.6983518589498
188                     United States  5237 28.5086881802559
189                           Uruguay  5088 81.0534591194968
190                        Uzbekistan   996 74.8995983935743
191                           Vanuatu  2135 89.9297423887588
192 Venezuela, Bolivarian Republic of  5222 84.2397548831865
193                          Viet Nam  3199 90.7471084713973
194                             Yemen  1527 94.2370661427636
195               Yemen Arab Republic  3291 82.4673351564874
196           Yemen People's Republic  2378   89.86543313709
197                        Yugoslavia  4650 80.8602150537634
198                            Zambia  4215 92.4317912218268
199                          Zanzibar     2                0
200                          Zimbabwe  2766 94.2154736080983

In [69]:
# to get a better idea of the votes, we sort the data using another DPLYR 'verb' ARRANGE()
by_country %>% arrange(percent_yes) # the default is ascending order
# the list can be sorted in descending order by invoking the desc() function inside arrange()
by_country %>% arrange(desc(percent_yes))

                            country total      percent_yes
1                          Zanzibar     2                0
2                     United States  5237 28.5086881802559
3                             Palau   777 30.6306306306306
4                            Israel  4790 35.0313152400835
5       Federal Republic of Germany  2151 39.8419339841934
6   Micronesia, Federated States of  1341 41.3124533929903
7                    United Kingdom  5218 42.6983518589498
8                            France  5171 43.2024753432605
9                  Marshall Islands  1468 47.8882833787466
10                          Belgium  5238 49.2554410080183
11                       Luxembourg  5169  51.054362545947
12                           Canada  5250 51.6571428571429
13                      Netherlands  5248 52.5342987804878
14                            Italy  4772 52.7661357921207
15                         Portugal  4675 53.8823529411765
16                        Australia  5245 55.4242135367016
17        Taiwan, Province of China  1233 57.0154095701541
18                          Denmark  5248 57.7553353658537
19                            Japan  4731  58.719086873811
20                           Norway  5243 58.8594316231165
21                          Georgia  1394 59.8278335724534
22                          Iceland  5059 60.0118600513935
23                      New Zealand  5243 60.5378600038146
24                            Nauru   606 60.8910891089109
25                           Latvia  1570 60.9554140127388
26                           Sweden  5232 62.0221712538226
27                          Estonia  1584 62.1212121212121
28                          Germany  1628 62.2235872235872
29                        Lithuania  1607 62.2277535780958
30             Moldova, Republic of  1506 62.7490039840637
...                             ...   ...              ...
171             Antigua and Barbuda  2521 91.7096390321301
172                          Angola  2950 92.2372881355932
173             Trinidad and Tobago  4205  92.294887039239
174                        Botswana  3778  92.350449973531
175                          Zambia  4215 92.4317912218268
176                         Namibia  1594 92.9736511919699
177                          Belize  2300 93.0434782608696
178                         Eritrea  1268 93.0599369085173
179                            Oman  3865 93.0659767141009
180               Brunei Darussalam  2546 93.0871956009426
181                          Guyana  4154 93.0909966297545
182                          Kuwait  4224 93.1818181818182
183                        Maldives  3761 93.1932996543473
184                          Gambia  2854 93.2025227750526
185                         Bahrain  3965 93.3417402269861
186                       Mauritius  3786 93.7665081880613
187                      Bangladesh  3631 93.8859818231892
188                           Qatar  3919 94.0801224802245
189                        Suriname  3278 94.1122635753508
190            United Arab Emirates  3877 94.1965437193707
191                        Zimbabwe  2766 94.2154736080983
192                           Yemen  1527 94.2370661427636
193                      Mozambique  3306  94.313369630974
194                      Cabo Verde  3153 94.5448778940691
195                         Comoros  2435 94.6201232032854
196                   Guinea-Bissau  2933 95.4653937947494
197                        Djibouti  3193 95.6467272157845
198           Sao Tome and Principe  2329 96.6509231429798
199                     Timor-Leste   697  96.700143472023
200                      Seychelles  1698 97.7031802120141

                            country total      percent_yes
1                        Seychelles  1698 97.7031802120141
2                       Timor-Leste   697  96.700143472023
3             Sao Tome and Principe  2329 96.6509231429798
4                          Djibouti  3193 95.6467272157845
5                     Guinea-Bissau  2933 95.4653937947494
6                           Comoros  2435 94.6201232032854
7                        Cabo Verde  3153 94.5448778940691
8                        Mozambique  3306  94.313369630974
9                             Yemen  1527 94.2370661427636
10                         Zimbabwe  2766 94.2154736080983
11             United Arab Emirates  3877 94.1965437193707
12                         Suriname  3278 94.1122635753508
13                            Qatar  3919 94.0801224802245
14                       Bangladesh  3631 93.8859818231892
15                        Mauritius  3786 93.7665081880613
16                          Bahrain  3965 93.3417402269861
17                           Gambia  2854 93.2025227750526
18                         Maldives  3761 93.1932996543473
19                           Kuwait  4224 93.1818181818182
20                           Guyana  4154 93.0909966297545
21                Brunei Darussalam  2546 93.0871956009426
22                             Oman  3865 93.0659767141009
23                          Eritrea  1268 93.0599369085173
24                           Belize  2300 93.0434782608696
25                          Namibia  1594 92.9736511919699
26                           Zambia  4215 92.4317912218268
27                         Botswana  3778  92.350449973531
28              Trinidad and Tobago  4205  92.294887039239
29                           Angola  2950 92.2372881355932
30              Antigua and Barbuda  2521 91.7096390321301
...                             ...   ...              ...
171            Moldova, Republic of  1506 62.7490039840637
172                       Lithuania  1607 62.2277535780958
173                         Germany  1628 62.2235872235872
174                         Estonia  1584 62.1212121212121
175                          Sweden  5232 62.0221712538226
176                          Latvia  1570 60.9554140127388
177                           Nauru   606 60.8910891089109
178                     New Zealand  5243 60.5378600038146
179                         Iceland  5059 60.0118600513935
180                         Georgia  1394 59.8278335724534
181                          Norway  5243 58.8594316231165
182                           Japan  4731  58.719086873811
183                         Denmark  5248 57.7553353658537
184       Taiwan, Province of China  1233 57.0154095701541
185                       Australia  5245 55.4242135367016
186                        Portugal  4675 53.8823529411765
187                           Italy  4772 52.7661357921207
188                     Netherlands  5248 52.5342987804878
189                          Canada  5250 51.6571428571429
190                      Luxembourg  5169  51.054362545947
191                         Belgium  5238 49.2554410080183
192                Marshall Islands  1468 47.8882833787466
193                          France  5171 43.2024753432605
194                  United Kingdom  5218 42.6983518589498
195 Micronesia, Federated States of  1341 41.3124533929903
196     Federal Republic of Germany  2151 39.8419339841934
197                          Israel  4790 35.0313152400835
198                           Palau   777 30.6306306306306
199                   United States  5237 28.5086881802559
200                        Zanzibar     2                0

In [72]:
# Now we remove countries that have fewer than 100 votes
by_country2 <- by_country %>% arrange(percent_yes) %>% filter(total >= 100)

                            country total      percent_yes
1                     United States  5237 28.5086881802559
2                             Palau   777 30.6306306306306
3                            Israel  4790 35.0313152400835
4       Federal Republic of Germany  2151 39.8419339841934
5   Micronesia, Federated States of  1341 41.3124533929903
6                    United Kingdom  5218 42.6983518589498
7                            France  5171 43.2024753432605
8                  Marshall Islands  1468 47.8882833787466
9                           Belgium  5238 49.2554410080183
10                       Luxembourg  5169  51.054362545947
11                           Canada  5250 51.6571428571429
12                      Netherlands  5248 52.5342987804878
13                            Italy  4772 52.7661357921207
14                         Portugal  4675 53.8823529411765
15                        Australia  5245 55.4242135367016
16        Taiwan, Province of China  1233 57.0154095701541
17                          Denmark  5248 57.7553353658537
18                            Japan  4731  58.719086873811
19                           Norway  5243 58.8594316231165
20                          Georgia  1394 59.8278335724534
21                          Iceland  5059 60.0118600513935
22                      New Zealand  5243 60.5378600038146
23                            Nauru   606 60.8910891089109
24                           Latvia  1570 60.9554140127388
25                           Sweden  5232 62.0221712538226
26                          Estonia  1584 62.1212121212121
27                          Germany  1628 62.2235872235872
28                        Lithuania  1607 62.2277535780958
29             Moldova, Republic of  1506 62.7490039840637
30                            Spain  4747 63.0714135243312
...                             ...   ...              ...
168             Antigua and Barbuda  2521 91.7096390321301
169                          Angola  2950 92.2372881355932
170             Trinidad and Tobago  4205  92.294887039239
171                        Botswana  3778  92.350449973531
172                          Zambia  4215 92.4317912218268
173                         Namibia  1594 92.9736511919699
174                          Belize  2300 93.0434782608696
175                         Eritrea  1268 93.0599369085173
176                            Oman  3865 93.0659767141009
177               Brunei Darussalam  2546 93.0871956009426
178                          Guyana  4154 93.0909966297545
179                          Kuwait  4224 93.1818181818182
180                        Maldives  3761 93.1932996543473
181                          Gambia  2854 93.2025227750526
182                         Bahrain  3965 93.3417402269861
183                       Mauritius  3786 93.7665081880613
184                      Bangladesh  3631 93.8859818231892
185                           Qatar  3919 94.0801224802245
186                        Suriname  3278 94.1122635753508
187            United Arab Emirates  3877 94.1965437193707
188                        Zimbabwe  2766 94.2154736080983
189                           Yemen  1527 94.2370661427636
190                      Mozambique  3306  94.313369630974
191                      Cabo Verde  3153 94.5448778940691
192                         Comoros  2435 94.6201232032854
193                   Guinea-Bissau  2933 95.4653937947494
194                        Djibouti  3193 95.6467272157845
195           Sao Tome and Principe  2329 96.6509231429798
196                     Timor-Leste   697  96.700143472023
197                      Seychelles  1698 97.7031802120141